BLOG_POSTS_FEED_URL = 'http://feeds2.feedburner.com/jaredgrippecom'
GOOGLE_PROFILE_URL  = 'http://www.google.com/s2/profiles/104443186735122889135'
TWITTER_URL         = 'http://www.twitter.com/jaredgrippe'
FACEBOOK_URL        = 'http://www.facebook.com/profile.php?id=509634696'
DEADLYICON_BLOG_URL = 'http://blog.deadlyicon.com/'
FLICKR_URL          = 'http://www.flickr.com/photos/deadlyicon/'
DELICIOUS_URL       = 'http://del.icio.us/deadlyicon'
LINKEDIN_URL        = 'http://www.linkedin.com/in/deadlyicon'
