development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  # Sqlite Settings
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

staging:
  # Sqlite Settings
  adapter: sqlite3
  database: db/staging.sqlite3
  pool: 5
  timeout: 5000

  # Mysql Settings
  # adapter: mysql
  # encoding: utf8
  # database: bort_staging
  # username: root
  # password:
  # pool: 5
  
production:
  adapter: mysql
  encoding: utf8
  host: mysql.jaredgrippe.com
  database: jaredgrippe_com
  username: jaredgrippe
  password: xaBrU45T
  pool: 5
